ZineClient/Controllers/OrganizationsController.cs
using Microsoft.AspNetCore.Authorization;
using ZineClient.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace ZineClient.Controllers
{
  [Authorize]
  public class OrganizationsController : Controller
  {
    private readonly ZineClientContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public OrganizationsController(UserManager<ApplicationUser> userManager, ZineClientContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [AllowAnonymous]
    public ActionResult Index()
    {
      List<Organization> model = _db.Organizations.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Organization organization)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      organization.Owner = currentUser;

      _db.Organizations.Add(organization);
      _db.ApplicationUserOrganization.Add(new ApplicationUserOrganization() { ApplicationUser = currentUser, OrganizationId = organization.OrganizationId });

      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      var thisOrganization = _db.Organizations
      .Include(o => o.ApplicationUsers)
      .ThenInclude(join => join.ApplicationUser)
      .Include(o => o.Zines)
      .FirstOrDefault(o => o.OrganizationId == id);

      return View(thisOrganization);
    }

    public ActionResult Edit(int id)
    {
      var thisOrganization = _db.Organizations.FirstOrDefault(organization => organization.OrganizationId == id);

      return View(thisOrganization);
    }

    [HttpPost]
    public ActionResult Edit(Organization organization)
    {
      _db.Entry(organization).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisOrganization = _db.Organizations.FirstOrDefault(organizations => organizations.OrganizationId == id);

      return View(thisOrganization);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisOrganization = _db.Organizations.FirstOrDefault(organizations => organizations.OrganizationId == id);
      _db.Organizations.Remove(thisOrganization);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddUser(int id)
    {
      var thisOrganization = _db.Organizations.FirstOrDefault(organizations => organizations.OrganizationId == id);

      return View(thisOrganization);
    }

    [HttpPost]
    public async Task<ActionResult> AddUser(Organization organization)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);

      _db.ApplicationUserOrganization.Add(new ApplicationUserOrganization() { ApplicationUser = currentUser, OrganizationId = organization.OrganizationId });
      _db.SaveChanges();

      return RedirectToAction("Index");
    }
  }
}

ZineClient/Controllers/TagsController.cs
using Microsoft.AspNetCore.Authorization;
using ZineClient.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using System;

namespace ZineClient.Controllers
{
  [Authorize]
  public class TagsController : Controller
  {
    private readonly ZineClientContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public TagsController(UserManager<ApplicationUser> userManager, ZineClientContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [AllowAnonymous]
    public ActionResult Index()
    {
      List<Tag> model = _db.Tags.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      // ViewBag.PostId = new SelectList(_db.Posts, "PostId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Tag tag)
    {
      // var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      // var currentUser = await _userManager.FindByIdAsync(userId);
      // tag.ApplicationUser = currentUser;

      _db.Tags.Add(tag);
      // if (PostId != 0)
      // {
      //   _db.PostTag.Add(new PostTag() { PostId = PostId, TagId = tag.TagId });
      // }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      var thisTag = _db.Tags
      .Include(tag => tag.Posts)
      .ThenInclude(join => join.Post)
      .FirstOrDefault(o => o.TagId == id);

      return View(thisTag);
    }

    public ActionResult Edit(int id)
    {
      var thisTag = _db.Tags.FirstOrDefault(tags => tags.TagId == id);

      return View(thisTag);
    }

    [HttpPost]
    public ActionResult Edit(Tag tag)
    {
      _db.Entry(tag).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisTag = _db.Tags.FirstOrDefault(tags => tags.TagId == id);

      return View(thisTag);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTag = _db.Tags.FirstOrDefault(tags => tags.TagId == id);
      _db.Tags.Remove(thisTag);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteTag(int joinId)
    {
      var joinEntry = _db.PostTag.FirstOrDefault(entry => entry.PostTagId == joinId);
      int thisPostId = joinEntry.PostId;

      _db.PostTag.Remove(joinEntry);
      _db.SaveChanges();

      return RedirectToAction("Details", "Posts", new { id = thisPostId });
    }
  }
}

ZineClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ZineClient</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&family=Source+Serif+Pro:wght@400;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/styles.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 justify-content-between">
            <div class="container" >
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Zine Maker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Organizations" asp-action="Index">Organizations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Zines" asp-action="Index">Zines</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="Index">Posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tags" asp-action="Index">Tags</a>
                        </li>                        
                    @* </ul> *@
                    @* <ul>                         *@
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown mr-auto">
                                <a class="nav-link text-dark dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @User.Identity.Name
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Account" asp-action="Index">My account</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-controller="Account" asp-action="Posts">My posts</a>
                                    @* <a class="dropdown-item" asp-controller="Account" asp-action="Zines">My zines</a> *@
                                    <a class="dropdown-item" asp-controller="Account" asp-action="Organizations">My organizations</a>
                                    <div class="dropdown-divider"></div>
                                    <form method="post">
                                    <input type="submit" class="dropdown-item btn btn-light mb-2" asp-controller="Account" asp-action="LogOff" value="Sign out"/>
                                    </form>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link text-dark dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sign in</a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Account" asp-action="Login">Sign in</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-controller="Account" asp-action="Register">Create an account</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container container-body">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 Andriy Veremyeyev & Krista Rutz - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            <br>
            <a></a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>